FROM node:20-alpine AS base
WORKDIR /app
RUN apk add --no-cache openssl
RUN corepack enable

COPY . .
RUN pnpm install
RUN pnpm --filter @caracal/api... build
RUN mkdir -p /app/logs/api /app/apps/api/uploads

STOPSIGNAL SIGTERM

WORKDIR /app/apps/api
CMD ["node", "dist/workers/bin-analysis-worker.js"]
