FROM node:20-alpine AS base
WORKDIR /app
RUN apk add --no-cache openssl
RUN corepack enable

COPY . .
RUN pnpm install
RUN pnpm --filter @caracal/api... build
RUN mkdir -p /app/logs/api /app/apps/api/uploads

EXPOSE 3001
STOPSIGNAL SIGTERM

WORKDIR /app/apps/api
CMD ["node", "dist/server.js"]
